version: '3.7'
services:
    django:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "5000:8000"
        volumes:
            - .:/app
        environment:
            - DATABASE_URL=postgresql://postgres:password@postgres:5432/parsing_websites
        depends_on:
            - postgres
            - redis
    postgres:
        image: postgres:12-alpine

        ports:
            - "5432:5432"
        environment:
            - SQL_ENGINE='django.db.backends.postgresql'
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=parsing_websites
    redis:
        image: redis:5.0.7
        ports:
            - "6379:6379"
    celery:
        build: .
        command: celery -A microserv.celery worker
        environment:
            - DATABASE_URL=postgresql://postgres:password@postgres:5432/parsing_websites
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
            - postgres
            - redis
            - django